INSERT INTO AIRFLOW0105.DEV.ETL_METADATA_4 (JOB_NAME, LAST_LOADED_DATE, IS_INITIALIZED, LAST_RUN_TS)
SELECT
  'stock_etl_4' AS JOB_NAME,
  '1900-01-01'::DATE AS LAST_LOADED_DATE,
  FALSE AS IS_INITIALIZED,
  CURRENT_TIMESTAMP() AS LAST_RUN_TS
WHERE NOT EXISTS (
  SELECT 1
  FROM AIRFLOW0105.DEV.ETL_METADATA_4
  WHERE JOB_NAME = 'stock_etl_4'
);