UPDATE AIRFLOW0105.DEV.ETL_METADATA_4
SET
  LAST_LOADED_DATE = (
    SELECT MAX(date)
    FROM AIRFLOW0105.DEV.STG_STOCK_HISTORY_4
  ),
  IS_INITIALIZED = TRUE,
  LAST_RUN_TS = CURRENT_TIMESTAMP()
WHERE JOB_NAME = 'stock_etl_4';