CREATE TABLE IF NOT EXISTS AIRFLOW0105.DEV.STG_STOCK_HISTORY_4
LIKE US_STOCK_DAILY.DCCM.STOCK_HISTORY;

CREATE TABLE IF NOT EXISTS AIRFLOW0105.DEV.STG_COMPANY_PROFILE_4
LIKE US_STOCK_DAILY.DCCM.COMPANY_PROFILE;

CREATE TABLE IF NOT EXISTS AIRFLOW0105.DEV.STG_SYMBOLS_4
LIKE US_STOCK_DAILY.DCCM.SYMBOLS;